#!/usr/bin/env ruby -Ilib

require './binary_tree'
require 'pry'

include BinaryTree

# initialize a $root object
$root = nil

# build the binary tree
%w{to be or not to be}.each do |value|
  if $root.nil?
    $root = Node.new(value)
  else
    $root.insert(Node.new(value))
  end
end

$root.each do |node|
  puts "#{node.value} (#{node.count})"
end

puts
puts "#{$root.size} values"
puts "#{$root.count_all} nodes"
